### ISSUE TITLE
LLM Evaluation: missing utils.py

### ISSUE THREAD

**Issue by sfc-gh-vtimofeenko** [Snowflake-Labs/snowflake-demo-streamlit#17]
[snowflake.yml](https://github.com/Snowflake-Labs/snowflake-demo-streamlit/blob/main/LLM%20Evaluation/snowflake.yml#L16) refers to `utils/utils.py`, but this file is not in the repository, rendering the app inoperable

**Comment by sfc-gh-asaini** [comment]
Thanks for reporting @sfc-gh-vtimofeenko 

Fixed in 7e05e2320fd1e40fb883375a6051cbc2a1791f91

Closing
