### ISSUE TITLE
SQL Optimizer Snowflake Cortex App cannot import Cortex

### ISSUE THREAD

**Issue by calder-holt** [Snowflake-Labs/snowflake-demo-streamlit#18]
The code for the SQL Optimizer Cortex App does not appear to be valid for Streamlit in Snowflake. When creating an app and using the source code it cannot import the Complete function.

```ModuleNotFoundError: No module named 'snowflake.cortex'
Traceback:
File "/usr/lib/python_udf/5759b01ddf3c89a7f38cfbfdd013907ebb882e6a2a64eb71d0c9c3880f2d0f2b/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
File "/tmp/appRoot/streamlit_app.py", line 3, in <module>
    from snowflake.cortex import Complete```

**Comment by sfc-gh-asaini** [comment]
Hi @calder-holt - Thanks for reporting this issue. Can you share the Python version, and versions of libraries you're trying to use in your app?

**Comment by calder-holt** [comment]
![image](https://github.com/user-attachments/assets/daa13ae9-eb2f-4859-b37c-dfbad11a594d)
- snowflake-snowpark-python = 1.23.0
- streamlit = 1.35.0
- python = 3.8
- snowflake = 1.0.0

Worth calling out these are all basically the defaults from SIS.

**Comment by calder-holt** [comment]
@sfc-gh-asaini any update?

**Comment by sfc-gh-asaini** [comment]
@calder-holt : You need to also import the `snowflake-ml-python` library to utilize Cortex. 

Added an `environment.yml` file to the repo in 977470e4a43ca5e05355ccdd651b5d08ca122e5f

**Comment by sfc-gh-asaini** [comment]
Closing issue. Feel free to reopen if you continue to see errors. Thanks
