### ISSUE TITLE
Error: Invalid Path 'External Access: Chat app using 3rd party LLM/README.md' Causing Checkout Failure on Windows

### ISSUE THREAD

**Issue by ineelhere** [Snowflake-Labs/snowflake-demo-streamlit#6]
### Issue Description
When cloning the repository `snowflake-demo-streamlit`, the checkout process fails due to an invalid path error for the file `External Access: Chat app using 3rd party LLM/README.md`. This only happens on a `windows` platform. 

**To Reproduce**

0. Get a windows instance.
1. Run the following command to clone the repository:
   ```bash
   git clone https://github.com/Snowflake-Labs/snowflake-demo-streamlit.git
   ```
2. Observe the error during the checkout process.

```
Cloning into 'snowflake-demo-streamlit'...
remote: Enumerating objects: 292, done.
remote: Counting objects: 100% (292/292), done.
remote: Compressing objects: 100% (223/223), done.
remote: Total 292 (delta 91), reused 246 (delta 54), pack-reused 0
Receiving objects: 100% (292/292), 15.48 MiB | 4.21 MiB/s, done.
Resolving deltas: 100% (91/91), done.
error: invalid path 'External Access: Chat app using 3rd party LLM/README.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

This issue seems to be caused by the invalid path name (for Windows) containing special characters like `:`. 

This could be resolved by renaming the folder with a valid character or a similar looking character ꞉ (U+A789 MODIFIER LETTER COLON) 

![image](https://github.com/Snowflake-Labs/snowflake-demo-streamlit/assets/64887729/9ee21dad-575f-495f-bfab-27b7adbf25f7)

Happy to help with a PR if this looks like a valid issue to be fixed. 🙂 

Thanks.

**Comment by sfc-gh-asaini** [comment]
Hey @ineelhere! Thanks for flagging this issue. Fixed in 8473e8443dda4a048bb716133ce5fd5def09b9cd
