### ISSUE TITLE
GET_PDF_RAW() not defined in creation_script.sql

### ISSUE THREAD

**Issue by ChuliangXiao** [Snowflake-Labs/snowflake-demo-streamlit#9]
https://github.com/Snowflake-Labs/snowflake-demo-streamlit/blob/fa77a421c61502e63759fc243f996ec6c7e7c3aa/Retrieval%20Augmented%20Generation%20(RAG)/streamlit_app.py#L39

`GET_PDF_RAW` has not been defined in `creation_script.sql` whereas `GET_PDF_CONTENT` return `str` instead `bytes`

**Comment by sfc-gh-asaini** [comment]
@ChuliangXiao : Thanks for catch. This is fixed in [dbf493e](https://github.com/Snowflake-Labs/snowflake-demo-streamlit/commit/dbf493ebe8df2e904b2616ea1a6203bc98f6230b)
